config/routes.rb
ExampleStore::Application.routes.draw do
  
  resources :groups do
    resources :carts do
      resources :items
    end
  end

  resources :sessions
  resources :users
  resources :bills

  #copied from railscast 250 - 270
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  get "welcome" => "welcome#index", :as => "welcome"
  root :to => "welcome#index"

  get "/groups/:group_id/carts/:cart_id/finalize" => "carts#finalize", :as => "finalize_cart"

  get '/return'=>'carts#return'

  get '/notification' => 'orders#notification'

  get 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  post 'groups/:id' => 'groups#add_group_member', :as => 'add_group_member'

  post 'bills/:id/status_paid' => 'bills#status_paid', :as => 'status_paid'
  post 'bills/:id/status_confirmed' => 'bills#status_confirmed', :as => "status_confirmed"

  get '/bills_confirm' => 'bills#confirm', :as => 'bills_confirm'
end

app/models/group.rb
class Group < ActiveRecord::Base
    attr_accessible :owner_id, :name, :id

    #set up the user which owns the group
    has_one :user

    #allow multiple members to join the group
    has_many :group_memberships
    has_many :members, through: :group_memberships, source: "user"

    #each group can have many carts
    has_many :group_carts
    has_many :lists, through: :group_carts, source: "cart"

<<<<<<< HEAD
    def get_owner_name
    	return User.find(self.owner_id).name
    end
=======
	def get_owner_name
		return User.find(self.owner_id).name
	end
>>>>>>> 263d1e7e3b2af26d3595abeb33e233a679c02f98

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :carts]
  before_action :check_group_membership, only: [:show, :edit, :update, :destroy, :carts]

  # GET /groups
  def index
    @groups = current_user.joined_groups
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    #set the group's owner to the current user
    params[:group][:owner_id] = current_user.id
    @group = Group.new(group_params)
    
    if @group.save
      @group_membership = GroupMembership.new({user_id: current_user.id, group_id: @group.id})
      if @group_membership.save
        redirect_to @group, notice: 'Group was successfully created.'
      else
        render action: 'new'
      end
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def add_group_member
    @add_user = User.find_by_email(add_group_member_params[:email])

    #Check if the user to add is already in the group    
    existing_groups = @add_user.joined_groups.map { |g| g.id.to_s } if @add_user
    if @add_user == nil
      flash[:error] = "Could not add member"
      redirect_to :controller => 'groups', action: 'show', :id => params[:id] 
    elsif existing_groups.include?(params[:id])
      flash[:warning] = "Member already in group"
      redirect_to :controller => 'groups', action: 'show', :id => params[:id] 
    else
      @group_membership = GroupMembership.new(user_id: @add_user.id, group_id: params[:id])
      if @group_membership.save
        flash[:notice] = "Member added."
       redirect_to :controller => 'groups', action: 'show', :id => params[:id]
      else
        flash[:error] = "Could not add member"
        redirect_to :controller => 'groups', action: 'show', :id => params[:id]
      end
    end
  end

  def cart
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:owner_id, :name)
    end

    def add_group_member_params
      params.require(:person).permit(:email)
    end

    def check_group_membership
      @member = @group.members.select {|m| m.id == current_user.id }
      if @member.length > 0
        return true
      else
        flash[:error] = "You are not a member of that group"
        redirect_to groups_url
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= render "layouts/navbar" %>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <legend>Name</legend>
    <%= f.text_field :name %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', groups_path, :class => 'btn' %>
  </div>

<% end %>

app/views/groups/carts.html.erb
<%= render "layouts/navbar" %>

<h1><% @group.name %> Lists</h1>

<table class="table table-striped">
  <tr>
    <th>Cart Name</th>
    <th>Finalized?</th>
    <th>Actions</th>
    <th></th>
  </tr>

<% @group.lists.each do |cart| %>
  <tr>
  
    <td>
      <%= link_to cart.cart_name, cart %>
    </td>

    <td>
      <% if cart.finalized %>
        Yes
      <% else %>
        No
      <% end %>
    </td>

    <td>
    <%= link_to 'Delete', group_cart_path(group_id: @group.id, id: cart.id), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a New Cart', new_cart_path, :class => 'btn btn-primary' %>

app/views/groups/edit.html.erb
<%= render "layouts/navbar" %>

<h1>Editing group</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<%= render "layouts/navbar" %>

<legend> 
  <h1>Groups</h1> 
  Need to get some comestibles? <br/> 
  Choose who you're shopping for and let's get some vitties!
</legend>

<br />

<table class="table table-striped">
  <thead>
    <tr>
      <th>Group Owner</th>
      <th>Group Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.get_owner_name %></td>
        <td><%= link_to group.name, group_carts_path(group_id: group.id), :class => "lead" %></td>
        <td><%= link_to 'Show Members', group, :class => 'btn' %></td>
        <td><%= link_to 'Edit Name', edit_group_path(group), :class => 'btn' %></td>
        <td><%= button_to 'Delete Group', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="form-actions">
  <%= link_to 'New Group', new_group_path, :class => 'btn' %>
</div>

app/views/groups/new.html.erb
<%= render "layouts/navbar" %>

<h1>Create a New Group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<%= render "layouts/navbar" %>

<legend> 
    <strong>Group Name:</strong>
    <h1><%= @group.name %></h1>
    <strong>Owner:</strong>
    <%= @group.get_owner_name %>
<<<<<<< HEAD
=======

>>>>>>> 263d1e7e3b2af26d3595abeb33e233a679c02f98
</legend> 

<p>
    <table id="group" class="table table-striped">
      <tr>
        <th>Members</th>
      </tr>
      <% for member in @group.members %>
        <tr class="<%= cycle :odd, :even %>">
          <td><%=h member.name %></td>
        </tr>
      <% end %>
    </table>

    <% if current_user.id == @group.owner_id %>
        <%= form_for :person do |f| %>
        <div class="field">
            <%= f.label :email, 'Add User by email' %><br>
            <%= f.text_field :email %>
        </div>
        <div class="actions">
            <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>
        <% end %>        
    <% end %>
</p>

<div class="form-actions">
    <%= link_to 'Edit', edit_group_path(@group), :class => 'btn' %>
    <%= link_to 'Back', groups_path, :class => 'btn' %>
</div>