config/routes.rb
ExampleStore::Application.routes.draw do
  
  resources :groups do
    resources :carts do
      resources :items
    end
  end

  resources :sessions
  resources :users
  resources :bills

  #copied from railscast 250 - 270
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  get "welcome" => "welcome#index", :as => "welcome"
  root :to => "welcome#index"

  get "/groups/:group_id/carts/:cart_id/finalize" => "carts#finalize", :as => "finalize_cart"

  get '/return'=>'carts#return'

  get '/notification' => 'orders#notification'

  get 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  post 'groups/:id' => 'groups#add_group_member', :as => 'add_group_member'

  post 'bills/:id/status_paid' => 'bills#status_paid', :as => 'status_paid'
  post 'bills/:id/status_confirmed' => 'bills#status_confirmed', :as => "status_confirmed"

  get '/bills_confirm' => 'bills#confirm', :as => 'bills_confirm'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :bills
	attr_accessible :cart_name

	has_one :group_cart
	has_one :group, through: :group_cart, source: "group"
	has_many :line_items, dependent: :destroy

	has_many :items, dependent: :destroy

	validates :cart_name, 
			  	presence: true, 
			  	length: { minimum: 3 },
			  	uniqueness: { case_sensitive: true }
	
	attr_accessible :cart_name

	def total_price
		items.to_a.sum(&:full_price)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_group
  before_action :check_group_membership

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def new
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])

    if @cart.save
      @group_cart = GroupCart.new(cart_id: @cart.id, group_id: @group.id)
      if @group_cart.save
        flash[:notice] = "Successfully created a new cart."
        redirect_to group_carts_url(group_id: @group.id)
      else 
        flash[:error] = "Could not create association"
        render :action => 'new'
      end  
    else
      render :action => 'new'
    end
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:group_id])
    @cart = Cart.find(params[:id])
    @cart.destroy
    flash[:notice] = "Successfully destroyed cart."
    redirect_to group_carts_path(@group, @cart)
  end

  def finalize
    @group = Group.find(params[:group_id])
    @cart = Cart.find(params[:cart_id])
    if @cart.update_attribute(:finalized, true)
      @cart.group.members.each do |ower|
        Bill.create(user_id: ower.id, cart_id: @cart.id, status: "unpaid", amount: (@cart.total_price / @cart.group.members.length))
      end

      redirect_to group_carts_path(@group, @cart)
    else
     render group_carts_path(@group, @cart)
    end 
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= render "layouts/navbar" %>

<%= form_for([@group, @group.lists.build]) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <legend>Choose a Name</legend>
    <%= f.text_field :cart_name %><br />
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', group_cart_path(id: @group.id), :class => 'btn' %>
  </div>

<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<%= render "layouts/navbar" %>

<h1><%= @group.name %>'s Carts</h1>

<table class="table table-striped">
  <tr>
    <th>Cart Name</th>
    <th>Finalized?</th>
    <th>Actions</th>
    <th></th>
  </tr>

<% @group.lists.each do |cart| %>
  <tr>
  
    <td>
      <%= link_to cart.cart_name, group_cart_url(id: cart.id, group_id: @group.id) %>
    </td>

    <td>
      <% if cart.finalized %>
        Yes
      <% else %>
        No
      <% end %>
    </td>

    <td>
    <%= button_to 'Delete', group_cart_path(id: cart.id, group_id: @group.id), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
    </td>

  </tr>
<% end %>
</table>

<br />

<div class="form-actions">
  <%= link_to 'Create a New Cart', new_group_cart_path, :class => 'btn' %>
  <%= link_to 'Back to Groups', groups_path, :class => 'btn' %>
</div>

app/views/carts/new.html.erb
<%= render "layouts/navbar" %>

<h1>Create a New Cart</h1>

<%= render 'form' %>

app/views/carts/show.html.erb
<%= render "layouts/navbar" %>

<h1> <%=@cart.cart_name%> </h1>

<legend> 
  <% if @cart.finalized%>
    This cart is finalized, no more items can be added
  <% else %>
    This cart is not yet finalized, you can keep adding items to it
  <% end %>
</legend> 

<table id="cart" class="table table-striped">
  <tr>
    <th>Item</th>
    <th>Qunatity</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% for line_item in @cart.items %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%=h line_item.name %></td>
      <td class="qty"><%= line_item.quantity %></td>
      <td class="price"><%= number_to_currency(line_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(line_item.full_price) %></td>

    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>

    <td class="amount owed" colspan="4">
      Amount each member owes: <%= number_to_currency @cart.total_price / @cart.group.members.length %>
    </td>

  </tr>
</table>

<div class="form-actions">
  <% if not @cart.finalized%>
      <%= link_to "Add Products to this Cart", new_group_cart_item_path(@group, @cart), :class => 'btn' %>
      <%= link_to 'Finalize this Cart', finalize_cart_path(@group, @cart), :class => 'btn btn-danger' %> 
  <% end %>
  <%= link_to 'Back to Carts', group_carts_path, :class => 'btn' %>
</div>