config/routes.rb
ExampleStore::Application.routes.draw do
  
  resources :groups do
    resources :carts do
      resources :items
    end
  end

  resources :sessions
  resources :users
  resources :bills

  #copied from railscast 250 - 270
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  get "welcome" => "welcome#index", :as => "welcome"
  root :to => "welcome#index"

  get "/groups/:group_id/carts/:cart_id/finalize" => "carts#finalize", :as => "finalize_cart"

  get '/return'=>'carts#return'

  get '/notification' => 'orders#notification'

  get 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  post 'groups/:id' => 'groups#add_group_member', :as => 'add_group_member'

  post 'bills/:id/status_paid' => 'bills#status_paid', :as => 'status_paid'
  post 'bills/:id/status_confirmed' => 'bills#status_confirmed', :as => "status_confirmed"

  get '/bills_confirm' => 'bills#confirm', :as => 'bills_confirm'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :cart
	validates :cart_id, presence: true

	attr_accessible :cart_id, :name, :quantity, :unit_price

	def full_price
		unit_price * quantity
	end
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, :set_group
  before_action :check_group_membership

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = @cart.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = @cart.items.create(item_params)
    redirect_to group_cart_path(@group, @cart)
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_cart
      @cart = Cart.find(params[:cart_id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :unit_price, :quantity, :category_id, :cart_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for ([@group, @cart, @cart.items.build]), :html => { :class => 'form-horizontal' } do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend><%= controller.action_name.capitalize %> Item</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :unit_price, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :unit_price, :class => 'text_field', :value => (number_with_precision(f.object.unit_price, :precision => 2) || 0) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :quantity, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :quantity, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', group_cart_path(@group, @cart), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/items/_item.html.erb
<li>
  This is an item
  <span class="content"><%= item.name %></span>
  <span class="timestamp">
    Quantity: <%= item.quantity %>
  </span>
  <span class="timestamp">
    Price: <%= item.unit_price %>
  </span>
</li>

app/views/items/edit.html.erb
<%= render "layouts/navbar" %>

<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render "layouts/navbar" %>

<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Category</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.unit_price %></td>
        <td><%= item.quantity %></td>
        <td><%= item.category_id %></td>
        <td><%= item.cart_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= render "layouts/navbar" %>

<h1>New item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<%= render "layouts/navbar" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @item.unit_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @item.cart_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>